steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:latest', '-t', 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:$COMMIT_SHA', '-t', 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:$BUILD_ID', '.']
  id: 'build-image-eventmeshtopubsubproducer'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
#  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:$COMMIT_SHA']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-eventmeshtopubsubproducer']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'eventmeshtopubsubproducer'
  - '--image'
  - 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--service-account'
  - 'workflow-cloudruninvoker@ingka-fulfilment-ordermgt-dev.iam.gserviceaccount.com'
  - '--allow-unauthenticated'
  waitFor: ['push-image-to-container-registry']
  id: 'deploy-to-cloud-run'
  timeout: 660s
#options:
#   machineType: 'N1_HIGHCPU_8'
#timeout: 660s
#tags: ['mytag1', 'mytag2']
#images: ['gcr.io/my-project/myimage']
