steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:latest', '-t', 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:$COMMIT_SHA', '-t', 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:$BUILD_ID', '.']
  id: 'build-image-eventmeshtopubsubproducer'
  env:
  - 'GCP_PROJECTID=ingka-fulfilment-ordermgt-dev'
  - 'GCP_TOPICID=ingka-ofd-order-execution-event-topic'
  - 'SOLACE_HOST=tcps://mr-q0vkfx9edol.messaging.solace.cloud:20008'
  - 'SOLACE_VPN=sweden-dc7-ocp3-dev-01'
  - 'SOLACE_USER=s-isomapp-u-ptpseelm'
  - 'SOLACE_PASSWORD=ateRch84'
  - 'SOLACE_QUEUENAME=ISOM_ORDER_DETAILS/1-5'
  - 'LOG_LEVEL=INFO'
  - 'PORT=8080'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
#  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:$COMMIT_SHA']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-eventmeshtopubsubproducer']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'eventmeshtopubsubproducer'
  - '--image'
  - 'gcr.io/ingka-fulfilment-ordermgt-dev/eventmeshtopubsubproducer:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--service-account'
  - 'workflow-cloudruninvoker@ingka-fulfilment-ordermgt-dev.iam.gserviceaccount.com'
  - '--allow-unauthenticated'
  waitFor: ['push-image-to-container-registry']
  id: 'deploy-to-cloud-run'
#options:
#   machineType: 'N1_HIGHCPU_8'
#timeout: 660s
#tags: ['mytag1', 'mytag2']
#images: ['gcr.io/my-project/myimage']
