spring:
   main:
    allow-bean-definition-overriding: true
    banner-mode: off
   application:
      name: eventmeshtopubsubproducer
   cloud:
    gcp:
      project-id: ingka-fulfilment-ordermgt-dev
      topic-id: ingka-ofd-order-execution-event-topic
      #credentials:
       # location: file:C:\Springboot\ingka-fulfilment-ordermgt-dev-48fa3abba22c.json
    
solace:
  jms:
    host: tcps://int-gke-euwe4-ingka.messaging.solace.cloud:55443
    msg-vpn: int-gke-euwe4
    client-username: isom-sa
    client-password: aXNvbS1zYQ==

sol:
  InQueues:  ISOM_ORDER_DETAILS/1-5
      
logging:
  level:
    root: INFO
