spring:
   main:
    allow-bean-definition-overriding: true
    banner-mode: off
   application:
      name: eventmeshtopubsubproducer
   cloud:
    gcp:
      project-id: ingka-fulfilment-ordermgt-dev
	   topic-id: ingka-ofd-order-execution-event-topic
      #credentials:
       # location: file:C:\Springboot\ingka-fulfilment-ordermgt-dev-48fa3abba22c.json
    
solace:
  jms:
    host: tcps://mr-q0vkfx9edol.messaging.solace.cloud:20008
    msg-vpn: sweden-dc7-ocp3-dev-01
    client-username: s-isomapp-u-ptpseelm
    client-password: ateRch84

sol:
  InQueues:  ISOM_ORDER_DETAILS/1-5

server:
  port: 8080
      
logging:
  level:
    root: INFO
